/* scripts/gen_mine_table.mjs
   Generates doc/MINE.md — the per-mine power-draw / solar-collector table.

   All game-time (24 h per game-day). Per body, at the UNDEPLETED / full-tonnage
   rate — power is fixed and does NOT fall off as the body depletes (that
   represents mining getting harder as a body empties, and keeps draws constant):

     rate_tpd     = fullRate / EXPLORE_DAYS_PER_SEC                (tonnes / game-day, ×1 framejack)
     E_perTonne   = escapeEnergy(bodyMass, 1 tonne, bodyRadius)   (J / tonne)
     kWd_perTonne = convertEnergy("kWd", { joules: E_perTonne })  (kWd / tonne)
     power_kW     = kWd_perTonne × rate_tpd                       (kWd·day⁻¹ = kW)
     collectors   = power_kW / 50                                 (one Solar Collector = 50 kW)

   Run:  node scripts/gen_mine_table.mjs
*/
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { BODIES, CONFIG, DT, DYSON_RING_COLLECTORS } from "../src/config.js";
import { EXPLORE_DAYS_PER_SEC } from "../src/explore.js";
import { escapeEnergy } from "../src/physics.js";
import { convertEnergy } from "../src/power_helpers.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const sb = JSON.parse(readFileSync(join(root, "src/stellar_bodies.json"), "utf8"));

const PAYLOAD_KG = 1000;        // 1 tonne — E_perTonne is J per tonne of metal lifted
const KW_PER_COLLECTOR = 50;    // one Solar Collector feeds 50 kW

const rows = BODIES.map((b) => {
  const s = sb[b.id];
  if (!s) return null;
  const ratePerDay = b.fullRate / EXPLORE_DAYS_PER_SEC;                 // tonnes / game-day
  const ePerTonne = escapeEnergy(s.mass_kg, PAYLOAD_KG, s.radius_m);    // J / tonne
  const kWdPerTonne = convertEnergy("kWd", { joules: ePerTonne });      // kWd / tonne
  const kW = kWdPerTonne * ratePerDay;                                  // kWd/tonne × t/day = kW
  const jPerDay = ePerTonne * ratePerDay;                              // J / game-day (for display)
  const collectors = kW / KW_PER_COLLECTOR;
  return { id: b.id, mineId: b.mineId, mineName: b.mineName, rep: s.body, ratePerDay, ePerTonne, jPerDay, kW, collectors };
}).filter(Boolean);

// ---- formatting helpers ----
const exp = (n) => n.toExponential(3);
const commas = (n, dp = 0) => n.toLocaleString("en-US", { maximumFractionDigits: dp, minimumFractionDigits: dp });
function human(n) {
  const u = [["", 1], ["K", 1e3], ["M", 1e6], ["B", 1e9], ["T", 1e12], ["Qa", 1e15], ["Qi", 1e18]];
  for (let i = u.length - 1; i >= 0; i--) if (n >= u[i][1]) return (n / u[i][1]).toFixed(2) + u[i][0];
  return n.toFixed(2);
}

const moonKw = rows.find((r) => r.id === "moon").kW;

let md = `# Mine Power Draw

Auto-generated by \`scripts/gen_mine_table.mjs\` — **do not edit by hand**, re-run the script.

Each mine's power draw is **fixed** at its full-tonnage (undepleted) rate. It does *not*
scale down as the body depletes: a mine keeps drawing as if still lifting the body's
peak tonnage, which represents extraction getting harder as the body empties (and keeps
power draws constant and predictable).

Everything here is **game-time** (24 h per game-day) — no real-world seconds anywhere.
The key identity is that escape energy expressed in **kWd per tonne**, times the mining
rate in **tonnes per game-day**, is a power in **kW** directly.

**Pipeline** (framejack ×1, so 1 tick = 1 game-day):

| step | formula |
|---|---|
| rate (t/game-day) | \`fullRate / EXPLORE_DAYS_PER_SEC\`  (= \`fullRate × DT\`) |
| escape energy / tonne (J) | \`escapeEnergy(bodyMass, 1 t, bodyRadius)\` |
| kWd / tonne | \`convertEnergy("kWd", { joules: … })\` |
| power (kW) | \`(kWd/tonne) × (t/day)\`  (kWd·day⁻¹ = kW) |
| collectors | \`kW / ${KW_PER_COLLECTOR}\`  (one Solar Collector = ${KW_PER_COLLECTOR} kW) |

Constants used: \`DT = ${DT}\`, \`EXPLORE_DAYS_PER_SEC = ${EXPLORE_DAYS_PER_SEC}\`, \`mineFrac = ${CONFIG.mineFrac}\`, \`minePaybackDays = ${CONFIG.minePaybackDays}\`, payload = 1 tonne, 24 h/day.

Escape energy uses the **heaviest moon** as the representative surface for each moon *system*
(Ceres for the belt); the mining **rate** uses the game's per-body \`fullRate\` (which for a
moon system is derived from the *combined* system mass). See \`src/stellar_bodies.json\`.

| mine | body | rate (t/day) | escape E/tonne (J) | energy/day (J) | power (kW) | collectors | ×Moon (kW) |
|---|---|--:|--:|--:|--:|--:|--:|
`;

for (const r of rows) {
  md += `| ${r.mineName} | ${r.rep} | ${commas(r.ratePerDay, r.ratePerDay < 10 ? 2 : 0)} | ${exp(r.ePerTonne)} | ${exp(r.jPerDay)} | ${human(r.kW)} | ${human(r.collectors)} | ${(r.kW / moonKw).toFixed(3)} |\n`;
}

md += `
> Suffixes: K=10³, M=10⁶, B=10⁹, T=10¹², Qa=10¹⁵, Qi=10¹⁸.

## Notes / knobs

- **Dynamic range is huge and compounds.** A mine's rate scales with body mass (\`fullRate ∝ mass\`)
  *and* its per-tonne lift cost scales with mass/radius, so the two multiply. The giant tier
  (Saturn, Jupiter) lands orders of magnitude above everything else — worth deciding whether that
  is the intended "scale up dramatically" wall or wants a damping factor.
- **Belt radar.** Asteroid-Penetrating Radar doubles belt yield. The rate above is the base
  (pre-radar) rate; if you want power to track actual throughput, double the belt's draw once
  radar is researched.
- **Moon systems.** Rate is from the combined system mass; the lift cost is modeled on the single
  heaviest moon. If you'd rather the two agree, either switch the rate to per-moon or the energy to
  a system-averaged body.
`;

mkdirSync(join(root, "doc"), { recursive: true });
writeFileSync(join(root, "doc/MINE.md"), md);

// ---- src/building_power.json — the game's power LUT ----
// Watts, signed: positive = draw (consumption), negative = generation.
// Keyed by building id (the mine's `mineId`), consumed by config.js.
const buildingPower = {};
for (const r of rows) buildingPower[r.mineId] = { powerUsageW: r.kW * 1000 };
// A Solar Collector generates 100× what an Asteroid Mine draws (negative = generation).
buildingPower.solar_collector = { powerUsageW: buildingPower.asteroid_mine.powerUsageW * -100 };
// A Dyson Ring Collector generates exactly DYSON_RING_COLLECTORS Solar Collectors' worth.
buildingPower.dyson_ring_collector = { powerUsageW: buildingPower.solar_collector.powerUsageW * DYSON_RING_COLLECTORS };
writeFileSync(join(root, "src/building_power.json"), JSON.stringify(buildingPower, null, 2) + "\n");

console.log(md);
console.log("wrote src/building_power.json:", JSON.stringify(buildingPower.asteroid_mine), "| collector:", JSON.stringify(buildingPower.solar_collector));
